### ISSUE TITLE
Moving forward to newer PHP versions

### ISSUE THREAD

**Issue by mbpcoder** [php-monsters/shaparak#4]
Given the potential performance and security enhancements in newer PHP versions (e.g., PHP 8.3 or 8.4),
I'm proposing a refactoring of the project to improve compatibility.
I'd like to know if this is an acceptable direction for the project before I begin the work.

**Comment by samuraee** [comment]
Hi Mahdi,

Thank you for your proposal! I’m happy to confirm that refactoring the project for compatibility with PHP 8.3 and 8.4 is an acceptable and valuable direction.

Please go ahead with your planned improvements, and feel free to share updates or open a pull request when ready.

Looking forward to seeing your contributions!

Best regards
