### ISSUE TITLE
Moving TestBank to a separate provider

### ISSUE THREAD

**Issue by mbpcoder** [php-monsters/shaparak#7]
In the TestBank provider, we utilized the actual provider and implemented it there instead of add some code in every provider

**Comment by samuraee** [comment]
Why?! I believe there has been a misunderstanding on your part. For every real provider, we have a corresponding test provider; for instance, Saman and SamanTest. Therefore, testBank is not a standalone provider to implement.

**Comment by mbpcoder** [comment]
I understand that adding a bit of code to every provider can become messy. 
By having a separate provider allowing us to create the testing provider in TestProvider and handle testing more efficiently.
And it can be extended to more testing options

**Comment by samuraee** [comment]
What do you mean by messy code? Nothing is messy in the drivers' code! Only one method that is responsible for providing URLs has been affected for BandTest compatibility (less than 2% of each driver code) and the rest are untouched. Furthermore, by setting SHAPARAK_MODE everything switches to testing mode and, in terms of efficiency, this feature don't affects performance. 
Maybe I didn't get your point! :/
